label var LBM_informeCII  "LBM - Informe entregada a CII"
label var LBM_recommend  "LBM - Resumen Ejecutivo con tabla del resumen de recommendaciones"
label var LBM_info_empresa  "LBM - Información breve de la empresa"
label var LBM_metodos_aud  "LBM - Se describen los métodos usados para la auditoría"
label var LBM_elect_uso  "LBM - Uso de electricidad"
label var LBM_elect_costo  "LBM - Costo de electricidad"
label var LBM_elect_GEI  "LBM - GEI de electricidad (indirecta) "
label var LBM_factor_emision  "LBM - Factor de Emision"
label var LBM_mhidro_GEI  "LBM - Tipo de hidrocarburo de mayor GEI"
label var LBM_mhidro_GEI_kwh  "LBM - Uso en KWH del hidrocarburo que produce la mayor GEI"
label var LBM_thidro_costo  "LBM - Costo de todos tipos de hidrocarburos consumidos"
label var LBM_thidro_GEI  "LBM - GEI de Gas/combustible (directa) total"
label var LBM_otro_GEI  "LBM - Tipo y cant. de otro tipo de GEI (no CO2)"
label var LBM_elec_pahorro_kwh  "LBM - Ahorro potencial en KWh de electricidad "
label var LBM_elec_pahorro_usd  "LBM - Ahorro potencial en UDS de electricidad"
label var LBM_elec_pahorro_GEI  "LBM - Reduccion potencial de GEI por ahorro de electricidad  (indirecta)  "
label var LBM_pfactor_emision  "LBM - Factor de Emision Potencial"
label var LBM_pa_mhidro_GEI  "LBM - Tipo de hidrocarburo que produce más GEI"
label var LBM_pa_mhidro_GEI_kwh  "LBM - Ahorro  potencial en KWH del tipo de hidrocarburo que produce más GEI"
label var LBM_pahorro_thidro_GEI  "LBM - Ahorro  potencial de TODOS Gas/combustible"
label var LBM_preduc_thidro_GEI  "LBM - Reduccion  potencial de GEI por TODOS Gas/combustible (directa) "
label var LBM_pahorro_otro_GEI  "LBM - Tipo y cant. de ahorro potencial de otro tipo de GEI (no CO2)"
label var LBM_inversion  "LBM - Inversión total necesaria"
label var LBM_Ahorro_EP  "LBM - Ahorro potencial Economico Proyectado "
label var LBM_Anios_recupera_P  "LBM - Periodo de recuperación"
label var LBM_TIR  "LBM - TIR"
label var LBM_VAN  "LBM - VAN"
label var LBM_Ahorro_elec_P  "LBM - Ahorro potencial de Electricidad  Proyectado (%) "
label var LBM_Ahorro_GEI_P  "LBM - Ahorro potencial de GEI  directo (de hidrocarburo) Proyectado (%) "
label var LBM_estim_incluye  "LBM - Incluyen los costos unitarios estimados de los nuevos equipos propuestos y el proceso de calculacion del costo de inversion? "
label var LBM_incluye_ppolit  "LBM - Incluyen también políticas energéticas que involucran el comportamiento de los personales?"
