label var country_2d  "Country_2d"
label var status  "Status"
label var registration  "Registration Date"
label var company  "Company Name"
label var name_f  "First Name"
label var name_l  "Last Name"
label var position  "Position"
label var telephone  "Telephone"
label var fax  "Fax"
label var email  "Email"
label var city  "Town-City"
label var province  "Department-Province"
label var country  "Country"
label var sector  "Sector"
label var market  "Market Focus"
label var age_0  "Years in Business (t=0)"
label var employees_0  "Employees (t=0)"
label var revenues_0  "Revenues (t=0)"
label var assets_0  "Assets (t=0)"
label var information_date  "Date Information"
label var audit_before  "Carried out an energy audit at your facilities before"
label var audit_bdate  "If so, when?"
label var personnel_participate  "Devote your personnel’s work time to participate?"
label var efprojects_desired  "Energy efficiency projects you would like to undertake"
label var age_1  "Years of the facility"
label var surface  "Total facility’s built surface (m2)"
label var employees_1  "Employees "
label var electric_consump_m  "Electric energy consumption measure (last year)"
label var electric_consump  "Electric energy consumption (last year)"
label var ngas_consump_m  "Natural Gas consumption measure (last year)"
label var ngas_consump  "Natural Gas consumption (last year)"
label var diesel_consump_m  "Diesel consumption measure (last year)"
label var diesel_consump  "Diesel consumption (last year)"
label var coal_consump_m  "Coal consumption measure (last year)"
label var coal_consump  "Coal consumption (last year)"
label var lpg_consump_m  "LPG consumption measure (last year)"
label var lpg_consump  "LPG consumption (last year)"
label var biom_consump_m  "Biomass consumption measure (last year)"
label var biom_consump  "Biomass consumption (last year)"
label var ohours  "Facility’s operating hours per week"
label var oweekends  "Does the facility operate in the weekends too?"
label var heating_age  "Number of years of facility’s main heating systems"
label var cooling_age  "Number of years of facility’s main cooling systems"
label var illumination  "Main illumination type"
label var pproc_steam  "Are steam/hot water used in the production processes?"
label var pproc_steam_c  "Comments8"
label var pproc_cair  "Is compressed air used in the production processes?"
label var pproc_cair_c  "Comments9"
label var pproc_emotor  "Are electric motors used in the production processes?"
label var pproc_emotor_c  "Comments10"
label var pproc_oven  "Are ovens and/or boilers used in the production processes?"
label var pproc_oven_c  "Comments11"
label var pproc_cooling  "Are industrial cooling and/or cooling chambers in the facility?"
label var pproc_cooling_c  "Comments12"
label var fossil_fuel   "What fossil fuel does your business use most?"
label var fossil_fuel_q  "How much of that fossil fuel does your company use per year?"
label var fossil_fuel_usd  "How much money does your company spend on fossil fuel(s) per year? (USD $)"
label var GREENPYME  "How did you find out about GREENPYME?"
label var multinational  "Is your company a multinational?"
label var web_address  "What is your web address?"
label var revenues_1  "Ingresos por ventas anuales "
label var assets_1  "Activos"
label var assets_comments  "Comments - Activos e ingresos"
label var LB_ccompromiso  "Carta de compromiso recibida"
label var LB_auditoria_fecha  "Fecha de la auditoria  realizada"
label var LB_informeCII  "LB - Informe entregada a CII"
label var LB_recommend  "LB - Resumen Ejecutivo con tabla del resumen de recommendaciones"
label var LB_info_empresa  "LB - Información breve de la empresa"
label var LB_metodos_aud  "LB - Se describen los métodos usados para la auditoría"
label var LB_elect_uso  "LB - Uso de electricidad"
label var LB_elect_costo  "LB - Costo de electricidad"
label var LB_elect_GEI  "LB - GEI de electricidad (indirecta) "
label var LB_factor_emision  "LB - Factor de Emision"
label var LB_mhidro_GEI  "LB - Tipo de hidrocarburo de mayor GEI"
label var LB_mhidro_GEI_uso  "LB - Uso del hidrocarburo que produce la mayor GEI"
label var LB_thidro_costo  "LB - Costo de todos tipos de hidrocarburos consumidos"
label var LB_thidro_GEI  "LB - GEI de Gas/combustible (directa) total"
label var LB_otro_GEI  "LB - Tipo y cant. de otro tipo de GEI (no CO2)"
label var LB_elec_pahorro_kwh  "LB - Ahorro potencial en KWh de electricidad "
label var LB_elec_pahorro_usd  "LB - Ahorro potencial en UDS de electricidad"
label var LB_elec_pahorro_GEI  "LB - Reduccion potencial de GEI por ahorro de electricidad  (indirecta)  "
label var LB_pfactor_emision  "LB - Factor de Emision Potencial"
label var LB_pa_mhidro_GEI  "LB - Tipo de hidrocarburo que produce más GEI"
label var LB_pa_mhidro_GEI_uso  "LB - Ahorro  potencial de el tipo de hidrocarburo que produce más GEI"
label var LB_pahorro_thidro_GEI  "LB - Ahorro  potencial de TODOS Gas/combustible"
label var LB_preduc_thidro_GEI  "LB - Reduccion  potencial de GEI por TODOS Gas/combustible (directa) "
label var LB_pahorro_otro_GEI  "LB - Tipo y cant. de ahorro potencial de otro tipo de GEI (no CO2)"
label var LB_inversion  "LB - Inversión total necesaria"
label var LB_pahorro  "LB - Ahorro potencial Economico Proyectado "
label var LB_recupera  "LB - Periodo de recuperación"
label var LB_TIR  "LB - TIR"
label var LB_VAN  "LB - VAN"
label var LB_pahorro_elect  "LB - Ahorro potencial de Electricidad  Proyectado (%) "
label var LB_pahorro_hidro_GEI  "LB - Ahorro potencial de GEI  directo (de hidrocarburo) Proyectado (%) "
label var LB_estim_incluye  "LB - Incluyen los costos unitarios estimados de los nuevos equipos propuestos y el proceso de calculacion del costo de inversion? "
label var LB_incluye_ppolit  "LB - Incluyen también políticas energéticas que involucran el comportamiento de los personales?"
label var AES_informe_CII  "Informe aprobada por CII"
label var AES_informe_IICDOCS  "Informe  en IICDOCS"
label var AES_entrega_fecha  "Fecha de entrega del informe AES a la empresa"
label var AES_csatisfaccion  "Carta de satisfaccion / constancia recibida"
label var AES_cuestionario  "Cuestionario de Evaluacion Recibido"
label var AES_pago_auditor  "Pago Hecho al Auditor?"
label var AED_interes  "Empresa interesada en AED?"
label var AED_potencial  "Empresa tiene potencial para una AED?"
label var AED_propuesta  "Propuesta para AED"
label var AED_bcomments  "Comments before AED"
label var AED_contrato_w  "Contrato personalizado (Word)"
label var AED_contrato_pdf  "Contrato personalizado  y firmado por CII (PDF)"
label var AED_contrato_firmado  "Contrato firmado por dos partes entregado a CII"
label var AED_contrato_ffirma  "Fecha de firma de contrato por la empresa"
label var AED_pago_cant  "Monto del pago de contrapartida"
label var AED_pago_comprob  "Prueba de pago de contrapartida (factura etc)"
label var AED_pago_fecha  "Fecha de recepcion de contrapartida de la empresa"
label var AED_fecha  "Fecha de la auditoria  detallada realizada"
label var AED_3m  "Has the audit been done within 3 months of the company signing the contract?"
label var LBD_informeCII  "LB Det - Informe entregada a CII"
label var LBD_recommend  "LB Det - Resumen Ejecutivo con tabla del resumen de recommendaciones"
label var LBD_info_empresa  "LB Det - Información breve de la empresa"
label var LBD_metodos_aud  "LB Det - Se describen los métodos usados para realizar la auditoría"
label var LBD_elect_uso  "LB Det - Uso de electricidad  "
label var LBD_elect_costo  "LB Det - Costo de electricidad  "
label var LBD_elect_GEI  "LB Det - GEI de electricidad (indirecta)   "
label var LBD_factor_emision  "LB Det - Factor de Emision "
label var LBD_mhidro_GEI  "LB Det - Tipo de hidrocarburo que produce la mayor cantidad de GEI  "
label var LBD_mhidro_GEI_uso  "LB Det - Uso del tipo de hidrocarburo que produce la mayor cantidad de GEI  "
label var LBD_thidro_costo  "LB Det - Costo de todos tipos de hidrocarburos consumidos "
label var LBD_thidro_GEI  "LB Det - GEI de Gas/combustible (directa)-suma de todos los combustibles "
label var LBD_otro_GEI  "LB Det - Tipo y cant. de otro tipo de GEI (no CO2)"
label var LBD_elec_pahorro_kwh  "LB Det - Ahorro potencial en KWh de electricidad "
label var LBD_elec_pahorro_usd  "LB Det - Ahorro potencial en UDS de electricidad"
label var LBD_elec_pahorro_GEI  "LB Det- Reduccion potencial de GEI por ahorro de electricidad  (indirecta)  "
label var LBD_pfactor_emision  "LB Det - Factor de Emision"
label var LBD_pa_mhidro_GEI  "LB Det - Tipo de hidrocarburo que produce más GEI"
label var LBD_pa_mhidro_GEI_uso  "LB Det - Ahorro  potencial de el tipo de hidrocarburo que produce más GEI"
label var LBD_pahorro_thidro_GEI  "LB Det - Ahorro  potencial de TODOS Gas/combustible"
label var LBD_preduc_thidro_GEI  "LB Det - Reduccion  potencial de GEI por TODOS Gas/combustible (directa) "
label var LBD_pahorro_otro_GEI  "LB Det - Tipo y cant. de ahorro potencial de otro tipo de GEI (no CO2)"
label var LBD_inversion  "LB Det - Inversión total necesaria"
label var LBD_pahorro  "LB Det - Ahorro potencial Economico Proyectado "
label var LBD_recupera  "LB Det - Periodo de recuperación"
label var LBD_TIR  "LB Det - TIR"
label var LBD_VAN  "LB Det - VAN"
label var LBD_pahorro_elect  "LB Det - Ahorro potencial de Electricidad  Proyectado (%) "
label var LBD_pahorro_hidro_GEI  "LB Det - Ahorro potencial de GEI  directo (de hidrocarburo) Proyectado (%) "
label var LBD_estim_incluye  "LB Det - Incluyen los costos unitarios estimados de los nuevos equipos propuestos y el proceso de calculacion del costo de inversion? "
label var LBD_incluye_ppolit  "LB Det - Incluyen también políticas energéticas que involucran el comportamiento de los personales?"
label var AED_informe_CII  "Informe detallado aprobada por CII    "
label var AED_informe_IICDOCS  "Informe  detallado en IICDOCS "
label var AED_csatisfaccion  "Carta de satisfaccion, constancia - doc # detallado"
label var AED_informe_fecha  "Fecha de entrega del informe AED a la empresa"
label var AED_finforme_N  "Entrega de informe final dentro de N meses despues de firma de contrato"
label var AED_informe_3m  "Has the report been delivered to the company within 3 months of contract signing?"
label var AED_informe_lfecha  "Fecha limite de entrega de informe"
label var AED_finforme_lfecha  "Fecha limite de entrega de informe final"
label var AED_cuestionario  "Cuestionario de Evaluacion Recibido"
label var M1_bcomments  "Comments before Monitoring 1"
label var M1_CII  "Enviado el resultado del 1er seguimiento a CII"
label var M1_fecha  "M1 - Date of 1st Monitoring"
label var M1_pfecha  "M1 - When can 1st Monitoring happen?"
label var M1_implement  "M1 - Han implementado algo?"
label var M1_light_1fecha  "M1 - Lighting - Fecha de la primera"
label var M1_light_costo  "M1 - Lighting -Costo de inversiones"
label var M1_light_kwh_ahorro  "M1 - Lighting - Ahorro en kWh del uso de electricidad"
label var M1_light_usd_ahorro  "M1 - Lighting - Ahorro del costo de electricidad ($USD)"
label var M1_light_GEI  "M1 - Lighting -GEI de electricidad (indirecta)"
label var M1_AC_1fecha  "M1 - AC - Fecha de la primera implementacion"
label var M1_AC_costo  "M1 - AC - Costo de inversiones"
label var M1_AC_kwh_ahorro  "M1 - AC - Ahorro en kWh del uso de electricidad"
label var M1_AC_usd_ahorro  "M1 - AC - Ahorro del costo de electricidad ($USD)"
label var M1_AC_GEI  "M1 - AC - GEI de electricidad (indirecta)"
label var M1_hwater_1fecha  "M1 - Water heating - Fecha de la primera implementacion"
label var M1_hwater_costo  "M1 - Water heating - Costo de inversiones"
label var M1_hwater_kwh_ahorro  "M1 - Water heating - Ahorro en kWh del uso de electricidad"
label var M1_hwater_usd_ahorro  "M1 - Water heating - Ahorro del costo de electricidad ($USD)"
label var M1_hwater_GEI  "M1 - Water heating - GEI de electricidad (indirecta)"
label var M1_compress_1fecha  "M1 - Compressors - Fecha de la primera implementacion"
label var M1_compress_costo  "M1 - Compressors - Costo de inversiones"
label var M1_compress_kwh_ahorro  "M1 - Compressors - Ahorro en kWh del uso de electricidad"
label var M1_compress_usd_ahorro  "M1 - Compressors - Ahorro del costo de electricidad ($USD)"
label var M1_compress_GEI  "M1 - Compressors - GEI de electricidad (indirecta)"
label var M1_eprod_1fecha  "M1 - Elec. production - Fecha de la primera implementacion"
label var M1_eprod_costo  "M1 - Elec. production - Costo de inversiones"
label var M1_eprod_kwh_ahorro  "M1 - Elec. production - Ahorro en kWh del uso de electricidad"
label var M1_eprod_usd_ahorro  "M1 - Elec. production - Ahorro del costo de electricidad ($USD)"
label var M1_eprod_GEI  "M1 - Elec. production - GEI de electricidad (indirecta)"
label var M1_oelec_medida  "M1 - Otros electricidad - Descripcion de Medida"
label var M1_oelec_1fecha  "M1 - Otros electricidad - Fecha de la primera implementacion"
label var M1_oelec_costo  "M1 - Otros electricidad - Costo de inversiones"
label var M1_oelec_kwh_ahorro  "M1 - Otros electricidad - Ahorro en kWh del uso de electricidad"
label var M1_oelec_usd_ahorro  "M1 - Otros electricidad - Ahorro del costo de electricidad ($USD)"
label var M1_oelec_GEI  "M1 - Otros electricidad - GEI de electricidad (indirecta)"
label var M1_electric_1fecha  "M1 - Total elec. - Fecha de la primera implementacion"
label var M1_electric_costo  "M1 - Total elec. - Costo de inversiones, totales hasta la fecha"
label var M1_electric_kwh_ahorro  "M1 - Total elec. - Ahorro en kWh del uso de electricidad"
label var M1_electric_usd_ahorro  "M1 - Total elec. - Ahorro del costo de electricidad ($USD)"
label var M1_electric_GEI  "M1 - Total elec. - GEI de electricidad (indirecta)"
label var M1_hidroc_1fecha  "M1 - Combustibles - Fecha de la primera implementacion"
label var M1_hidroc_costo  "M1 - Combustibles - Costo de inversiones"
label var M1_hidroc  "M1 - Tipo de hidrocarburo"
label var M1_hidroc_uso  "M1 - Ahorro del uso de hidrocarburo, con la unidad apropiada"
label var M1_hidroc_ahorro_costo  "M1 - Ahorro del costo de hidrocarburo"
label var M1_GEI  "M1 - GEI de Gas/combustible (directa)"
label var M1_otro_GEI  "M1 - Tipo y cantidad de otro tipo de GEI (no CO2)"
label var M1_produccion  "M1 - Cambio en niveles de produccion anualizados desde la auditoria"
label var M1_motivo_costs  "M1 - Motivo - Costs"
label var M1_motivo_environment  "M1 - Motivo - Environment"
label var M1_motivo_productivity  "M1 - Motivo - Productivity, Quality"
label var M1_barrera_financing  "M1 - Barrera - Financing"
label var M1_barrera_technical  "M1 - Barrera - Technical Information"
label var M1_barrera_other  "M1 - Barrera - Other"
label var M1_quote  "M1 - Quote from the business"
label var M1_additionalEE  "M1 - Additional EE Measures Implemented"
label var M1_additionalEE_value  "M1 - Value of additional EE measures implemented"
label var M1_additionalEE_fneed  "M1 - How much more EE financing needed?"
label var M1_nonEE_fneed  "M1 - Do they need financing for non-EE projects, and if so for what?"
label var M1_nonEE_fneed_q  "M1 - How much non-EE financing needed?"
label var M1_aCII  "M1 - 1er seguimiento aprobado por CII"
label var M2_bcomments  "M1 - Comments before Monitoring 2"
label var M2_CII  "M2 - Enviar el resultado del 2o seguimiento a CII"
label var M2_fecha  "M2 - Date of 2nd Monitoring"
label var M2_pfecha  "M2 - When can 2nd Monitoring happen?"
label var M2_implement  "M2 - Han implementado algo ADICIONAL desde el MONITOREO 1?"
label var M2_light_1fecha  "M2 - Lighting - Fecha de la primera"
label var M2_light_costo  "M2 - Lighting -Costo de inversiones"
label var M2_light_kwh_ahorro  "M2 - Lighting - Ahorro en kWh del uso de electricidad"
label var M2_light_usd_ahorro  "M2 - Lighting - Ahorro del costo de electricidad ($USD)"
label var M2_light_GEI  "M2 - Lighting -GEI de electricidad (indirecta)"
label var M2_AC_1fecha  "M2 - AC - Fecha de la primera implementacion"
label var M2_AC_costo  "M2 - AC - Costo de inversiones"
label var M2_AC_kwh_ahorro  "M2 - AC - Ahorro en kWh del uso de electricidad"
label var M2_AC_usd_ahorro  "M2 - AC - Ahorro del costo de electricidad ($USD)"
label var M2_AC_GEI  "M2 - AC - GEI de electricidad (indirecta)"
label var M2_hwater_1fecha  "M2 - Water heating - Fecha de la primera implementacion"
label var M2_hwater_costo  "M2 - Water heating - Costo de inversiones"
label var M2_hwater_kwh_ahorro  "M2 - Water heating - Ahorro en kWh del uso de electricidad"
label var M2_hwater_usd_ahorro  "M2 - Water heating - Ahorro del costo de electricidad ($USD)"
label var M2_hwater_GEI  "M2 - Water heating - GEI de electricidad (indirecta)"
label var M2_compress_1fecha  "M2 - Compressors - Fecha de la primera implementacion"
label var M2_compress_costo  "M2 - Compressors - Costo de inversiones"
label var M2_compress_kwh_ahorro  "M2 - Compressors - Ahorro en kWh del uso de electricidad"
label var M2_compress_usd_ahorro  "M2 - Compressors - Ahorro del costo de electricidad ($USD)"
label var M2_compress_GEI  "M2 - Compressors - GEI de electricidad (indirecta)"
label var M2_eprod_1fecha  "M2 - Elec. production - Fecha de la primera implementacion"
label var M2_eprod_costo  "M2 - Elec. production - Costo de inversiones"
label var M2_eprod_kwh_ahorro  "M2 - Elec. production - Ahorro en kWh del uso de electricidad"
label var M2_eprod_usd_ahorro  "M2 - Elec. production - Ahorro del costo de electricidad ($USD)"
label var M2_eprod_GEI  "M2 - Elec. production - GEI de electricidad (indirecta)"
label var M2_oelec_medida  "M2 - Otros electricidad - Descripcion de Medida"
label var M2_oelec_1fecha  "M2 - Otros electricidad - Fecha de la primera implementacion"
label var M2_oelec_costo  "M2 - Otros electricidad - Costo de inversiones"
label var M2_oelec_kwh_ahorro  "M2 - Otros electricidad - Ahorro en kWh del uso de electricidad"
label var M2_oelec_usd_ahorro  "M2 - Otros electricidad - Ahorro del costo de electricidad ($USD)"
label var M2_oelec_GEI  "M2 - Otros electricidad - GEI de electricidad (indirecta)"
label var M2_electric_1fecha  "M2 - Total elec. - Fecha de la primera implementacion"
label var M2_electric_costo  "M2 - Total elec. - Costo de inversiones, totales hasta la fecha"
label var M2_electric_kwh_ahorro  "M2 - Total elec. - Ahorro en kWh del uso de electricidad"
label var M2_electric_usd_ahorro  "M2 - Total elec. - Ahorro del costo de electricidad ($USD)"
label var M2_electric_GEI  "M2 - Total elec. - GEI de electricidad (indirecta)"
label var M2_hidroc_1fecha  "M2 - Combustibles - Fecha de la primera implementacion"
label var M2_hidroc_costo  "M2 - Combustibles - Costo de inversiones"
label var M2_hidroc  "M2 - Tipo de hidrocarburo"
label var M2_hidroc_uso  "M2 - Ahorro del uso de hidrocarburo, con la unidad apropiada"
label var M2_hidroc_ahorro_costo  "M2 - Ahorro del costo de hidrocarburo"
label var M2_GEI  "M2 - GEI de Gas/combustible (directa)"
label var M2_otro_GEI  "M2 - Tipo y cantidad de otro tipo de GEI (no CO2)"
label var M2_produccion  "M2 - Cambio en niveles de produccion anualizados desde la auditoria"
label var M2_motivo_costs  "M2 - Motivo - Costs"
label var M2_motivo_environment  "M2 - Motivo - Environment"
label var M2_motivo_productivity  "M2 - Motivo - Productivity, Quality"
label var M2_barrera_financing  "M2 - Barrera - Financing"
label var M2_barrera_technical  "M2 - Barrera - Technical Information"
label var M2_barrera_other  "M2 - Barrera - Other"
label var M2_quote  "M2 - Quote from the business"
label var M2_additionalEE  "M2 - Additional EE Measures Implemented"
label var M2_additionalEE_value  "M2 - Value of additional EE measures implemented"
label var M2_additionalEE_fneed  "M2 - How much more EE financing needed?"
label var M2_nonEE_fneed  "M2 - Do they need financing for non-EE projects, and if so for what?"
label var M2_nonEE_fneed_q  "M2 - How much non-EE financing needed?"
label var M2_aCII  "M2 - 2o seguimiento aprobado por CII"
label var total_meses  "Ahorro Total - Meses transcurrido hasta la primera implementacion"
label var total_dias  "Ahorro Total - Days before the company did first implementation?"
label var total_costo  "Ahorro Total - Costo de inversiones, totales hasta la fecha"
label var total_ahorro  "Ahorro Total - Ahorro economico obtenido"
label var total_recupera  "Ahorro Total - Periodo de recuperación de Inversion (PRI) Simple"
label var total_GEI  "Ahorro Total - GEI (indirecta e directa)"
label var total_ahorro_LB  "Ahorro Económico Total - Comparacion con linea base (%)"
label var total_ahorro_GEI_LB  "Ahorro GEI Total - Comparacion con linea base (%)"
label var total_ahorro_PI  "Ahorro Económico Total - Comparacion con propuesta inicial (%)"
label var total_ahorro_GEI_PI  "Ahorro GEI Total - Comparacion con propuesta inicial (%)"
label var nonIIC_financing  "Connected with non-IIC Financing?"
label var IIC_financing  "Connected with IIC Financing?"
label var IIC_sugfinancing  "Suggested for IIC Financing (>$100k)?"
label var SEA_DEA  "Companies which have received both SEA and DEA"
label var total_electr_costo  "Sum of Costo de electricidad"
label var total_ninversión  "Sum of Inversión necesaria (todos proyectos)"
label var total_pahorro  "Sum of Ahorro Economico Proyectado"
label var total_remsavings  "Remaining annual savings to be achieved"
